spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kstock
    username: kangmin
    password: 1234
  data:
    mongodb:
      uri: mongodb://localhost:27017/lottery
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 클라이언트 Id
            client-secret: 클라이언트 비밀번호
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: email, profile
app:
  auth:
    tokenSecret: 토큰 비밀번호
    tokenExpriationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:9090/oauth2/redirect
